#!/bin/bash
#PBS -N NBFNet
#PBS -l select=1:mpiprocs=1:ngpus=1
#PBS -l walltime=3:00:00
#PBS -j oe
#PBS -o /home/users/ntu/zhixian5/NBFNet_Context_Pooling/pbs_log/
#PBS -e /home/users/ntu/zhixian5/NBFNet_Context_Pooling/pbs_log/
#PBS -P 12003906
#PBS -q normal

cd NBFNet_Context_Pooling/

module load cuda/11.6.2
nvidia-smi



export CUBLAS_WORKSPACE_CONFIG=:16:8
export PYTHONUNBUFFERED=1
/home/users/ntu/zhixian5/anaconda3/bin/conda run -n py310 --no-capture-output python /home/users/ntu/zhixian5/NBFNet_Context_Pooling/script/run.py -c config/inductive/fb15k237.yaml --gpus [0] --version v1


