output_dir: ~/scratch/experiments/

dataset:
  class: FB15k-237
  root: ~/datasets/knowledge_graphs/
  version: {{ version }}

model:
  class: DistinctiveNBFNet
  input_dim: 32
  hidden_dims: [32, 32, 32, 32, 32, 32]
  message_func: distmult
  aggregate_func: pna
  dependent: yes
  layer_norm: no
  remove_one_hop: no
  short_cut: yes




task:
  num_negative: 32
  strict_negative: yes
  adversarial_temperature: 0.5
  metric: [mr, mrr, hits@1, hits@3, hits@10, hits@10_50]

optimizer:
  class: Adam
  lr: 0.0007

train:
  gpus: {{ gpus }}
  batch_size: 16
  num_epoch: 20
  log_interval: 10000

