output_dir: ~/scratch/experiments/

dataset:
  class: WN18RR
  root: ~/datasets/knowledge_graphs/
  version: {{ version }}

model:
  class: DistinctiveNBFNet
  input_dim: 32
  hidden_dims: [32, 32, 32, 32, 32, 32]
  message_func: distmult
  aggregate_func: pna
  dependent: yes
  layer_norm: no
  remove_one_hop: yes
  short_cut: yes

task:
  num_negative: 32
  strict_negative: yes
  adversarial_temperature: 1
  metric: [mr, mrr, hits@1, hits@3, hits@10, hits@10_50]

optimizer:
  class: Adam
  lr: 1e-2

train:
  gpus: {{ gpus }}
  batch_size: 32
  num_epoch: 20
  log_interval: 100
